version: '3'

volumes:
  metropark_02_local_postgres_data: {}
  metropark_02_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: metropark_02_local_django
    container_name: metropark_02_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: metropark_02_production_postgres
    container_name: metropark_02_local_postgres
    volumes:
      - metropark_02_local_postgres_data:/var/lib/postgresql/data
      - metropark_02_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: metropark_02_local_docs
    container_name: metropark_02_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./metropark_02:/app/metropark_02:z
    ports:
      - '9000:9000'
    command: /start-docs
