# Generated by Django 4.1.9 on 2023-06-26 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fine",
            name="israeli_id",
        ),
    ]
